- hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  become_method: sudo
  tasks:
    - name: Create S3 bucket
      s3_bucket:
        name: my-bucket-09111996
        state: present
        region: ap-south-1
