- hosts: localhost
  connection: local
  gather_facts: False
  become: yes
  become_method: sudo
  vars:
    ansible_user: jenkins
    ansible_become_user: root
    ansible_python_interpreter:  /usr/local/lib/python3.10/dist-packages
  tasks:
    - name: Create S3 bucket
      s3_bucket:
        name: my-bucket-09111996
        state: present
        region: ap-south-1
