- hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create S3 bucket
      s3_bucket:
        name: my-bucket-09111996
        state: present
